name: Publish Python package

on:
  release:
    types: [created]

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python3 -m pip install --user --upgrade setuptools wheel
        pip install -e .[test]
    - name: Build the packages
      run: >-
        python3 setup.py sdist bdist_wheel
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypiToken }}

